G_kwargs:
  class_name: 'training.networks_KPG_stylegan3.Generator'
  alpha_schedule:
    inline: 'lambda x,y : 1 / (y / x)'
    x: 'batch_size'
    y: 'loop_kwargs.alpha_kimg' 
  target_resolution:
    inline: 'lambda x : x[0]'
    x: 'data.resolution'
  magnitude_ema_beta: 
    inline: 'lambda x : 0.5 ** (x / (20 * 1e3))'
    x: 'batch_size'

D_kwargs:
  class_name: 'training.networks_KPG_stylegan3.Discriminator'
  alpha_schedule:
    inline: 'lambda x,y : 1 / (y / x)'
    x: 'batch_size'
    y: 'loop_kwargs.alpha_kimg' 
  target_resolution:
    inline: 'lambda x : x[0]'
    x: 'data.resolution'

data:
  resolution: [32, 64, 128, 256, 512]

loop_kwargs:
  class_name: 'training.training_loop.ProgressiveTrainer'
  alpha_kimg: 600000 # 600K images 